export const photoCatalog = [
  { id: 'photo-01', original: '1.webp' },
  { id: 'photo-02', original: '11.webp' },
  { id: 'photo-03', original: '2.webp' },
  { id: 'photo-04', original: '20.webp' },
  { id: 'photo-05', original: '3.webp' },
  { id: 'photo-06', original: '30.webp' },
  { id: 'photo-07', original: '4.webp' },
  { id: 'photo-08', original: '40.webp' },
  { id: 'photo-09', original: '5.webp' },
  { id: 'photo-10', original: '50.webp' },
  { id: 'photo-11', original: '60.webp' },
  { id: 'photo-12', original: '70.webp' },
  { id: 'photo-13', original: 'mu11.jpg' },
  { id: 'photo-14', original: 'mu12.jpg' },
  { id: 'photo-15', original: 'mu13.jpg' },
  { id: 'photo-16', original: 'mu5.jpg' },
  { id: 'photo-17', original: 'mu6.jpg' },
  { id: 'photo-18', original: 'mu7.jpg' },
]
